### ISSUE TITLE
saasherder.py:_process_template does not work in private GitHub repositories

### ISSUE THREAD

**Issue by gastaldi** [app-sre/qontract-reconcile#2106]
When configuring a `/app-sre/saas-file-2.yml` pointing to a private GitHub repository, the following error happens (even having `app-sre-bot` with write access):
```
[2022-01-21 18:14:24] [ERROR] [saasherder.py:_process_template:479] - [https://github.com/quarkusio/registry.quarkus.redhat.com//openshift/template.yaml:9178abdbcb01f35c09473113afb67239d74ad85d] error fetching template: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
[2022-01-21 18:14:24] [ERROR] [saasherder.py:_process_template:479] - [https://github.com/quarkusio/registry.quarkus.redhat.com//openshift/template.yaml:main] error fetching template: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
```

The error is gone if I change the repository visibility to public

**Comment by maorfr** [comment]
You need to use the `authentication.code` section to specify credentials to use to access the repository.

If you invite @app-sre-bot to your repository with Write access, you should be able to use the same credentials commonly found within app-interface.

**Comment by gastaldi** [comment]
Adding the `authentication.code` snippet does not seem to resolve the problem. I have the @app-sre-bot with Write access and the following snippet and I still get the same error in the build:

```yaml
authentication:
  code:
    path: app-sre/creds/github-app-sre-bot
    field: openshift-saas-deploy
```

**Comment by gastaldi** [comment]
Actually the original error is no longer shown, but I still get the following:


```bash
Traceback (most recent call last):
  File "/usr/local/bin/qontract-reconcile", line 8, in <module>
    sys.exit(integration())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/reconcile/cli.py", line 1215, in github_repo_permissions_validator
    run_integration(reconcile.github_repo_permissions_validator,
  File "/usr/local/lib/python3.9/site-packages/reconcile/cli.py", line 439, in run_integration
    func_container.run(dry_run, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/reconcile/github_repo_permissions_validator.py", line 50, in run
    repo = gh.get_repo(repo_name)
  File "/usr/local/lib/python3.9/site-packages/github/MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
```

**Comment by gastaldi** [comment]
Changing to `ci-int` fixes the problem, I'll close this issue meanwhile
