### ISSUE TITLE
Handle qontract-reconcile resource not found exceptions

### ISSUE THREAD

**Issue by aditya-konarde** [app-sre/qontract-reconcile#26]
## What I did

```
(venv) [akonarde@katana qontract-reconcile]$ qontract-reconcile --config=config.toml --dry-run openshift-resources-annotate cluster namespace ConfigMap some-config

Traceback (most recent call last):
  File "/home/akonarde/Git/qontract-reconcile/venv/lib/python3.7/site-packages/reconcile-0.1.0-py3.7.egg/reconcile/openshift_resources_annotate.py", line 49, in run
    resource = oc.get(namespace, kind, name)
  File "/home/akonarde/Git/qontract-reconcile/venv/lib/python3.7/site-packages/reconcile-0.1.0-py3.7.egg/utils/oc.py", line 51, in get
    return self._run_json(cmd)
  File "/home/akonarde/Git/qontract-reconcile/venv/lib/python3.7/site-packages/reconcile-0.1.0-py3.7.egg/utils/oc.py", line 89, in _run_json
    out = self._run(cmd)
  File "/home/akonarde/Git/qontract-reconcile/venv/lib/python3.7/site-packages/reconcile-0.1.0-py3.7.egg/utils/oc.py", line 81, in _run
    raise StatusCodeError(err)
utils.oc.StatusCodeError: b'Error from server (NotFound): configmaps "cloudwatch-exporter-config" not found\n'
```

In the above case, the said configmap was not present in the namespace. 

## Expected output:
Perhaps directly show utils.oc.StatusCodeError's message: `Error from server (NotFound): configmaps "some-config" not found`

**Comment by maorfr** [comment]
@aditya-konarde isn't this what it says?

**Comment by maorfr** [comment]
closing this as we no longer annotate.
